model:  # size: 79,413,082
  type: MyBertModelForMlm
  base_config:
    type: MyBertModel
    device: cuda
    dtype: float32
    vocab_size: 50266
    max_sequence_length: 512
    output_hidden_states: false
    output_attentions: false
    hidden_size: 768
    num_encoder_layers: 4
    num_attention_heads: 12
    gated_attention: true
    mlp_type: gated(gelu)
  tie_word_embeddings: true
