# !/bin/bash

uv run scripts/train.py \
    --model="ajdsouza/roberta-extended" \
    --memmap_path='test_data' \
    --batch_size=2 \
    --block_size=128 \
    --d_model=256 \
    --d_ffn=512 \
    --n_heads=4 \
    --n_layer=2 \
    --activation='silu' \
    --mlp_type='gated' \
    --norm_position='prenorm' \
    --attention_dropout=0.1 \
    --hidden_dropout=0.1 \
    --layernorm_eps=1e-12 \
    --vocab_size=50265 \
    --lr=5e-5 \
    --beta1=0.9 \
    --beta2=0.99 \
    --weight_decay=0.05 \
    --checkpoint_dir='ckpt' \
    --log_file='logs/logfile.log' \
    --wandb_entity="tororo" \
    --wandb_project_name="BERT Pretraining Test" \
    --wandb_run_name="added hidden and attention dropout and layernorm eps" \
    --device="mps" \
    --grad_accumulation_steps=4 \
    --num_epochs=1 \
    --save_every=100 \
    --eval_every=50 \
    --num_train_tokens=1_000_000 \
    --num_val_tokens=1_000 \